-- Drop table if it already exists
DROP TABLE IF EXISTS cleaned_dataset;

-- Create table
CREATE TABLE cleaned_dataset (
    type                          VARCHAR(50),
    days_for_shipping_real        INTEGER,
    days_for_shipment_scheduled   INTEGER,
    benefit_per_order             NUMERIC(12, 6),
    sales_per_customer            NUMERIC(12, 6),
    delivery_status               VARCHAR(100),
    late_delivery_risk            INTEGER,
    category_id                   INTEGER,
    category_name                 VARCHAR(150),
    customer_city                 VARCHAR(100),
    customer_country              VARCHAR(100),
    customer_fname                VARCHAR(100),
    customer_id                   INTEGER,
    customer_lname                VARCHAR(100),
    customer_segment              VARCHAR(100),
    customer_state                VARCHAR(100),
    department_id                 INTEGER,
    department_name               VARCHAR(150),
    market                        VARCHAR(100),
    order_city                    VARCHAR(100),
    order_country                 VARCHAR(100),
    order_customer_id             INTEGER,
    order_date                    VARCHAR(50),
    order_id                      INTEGER,
    order_item_cardprod_id        INTEGER,
    order_item_discount           NUMERIC(12, 6),
    order_item_discount_rate      NUMERIC(12, 6),
    order_item_id                 INTEGER,
    order_item_product_price      NUMERIC(12, 6),
    order_item_profit_ratio       NUMERIC(12, 6),
    order_item_quantity           INTEGER,
    sales                         NUMERIC(12, 6),
    order_item_total              NUMERIC(12, 6),
    order_profit_per_order        NUMERIC(12, 6),
    order_region                  VARCHAR(100),
    order_state                   VARCHAR(100),
    order_status                  VARCHAR(100),
    product_card_id               INTEGER,
    product_category_id           INTEGER,
    product_name                  VARCHAR(255),
    product_price                 NUMERIC(12, 6),
    product_status                INTEGER,
    shipping_date                 VARCHAR(50),
    shipping_mode                 VARCHAR(100),
    shipping_delay_days           INTEGER,
    is_late                       INTEGER,
    order_year                    INTEGER,
    order_month                   INTEGER,
    order_month_name              VARCHAR(20),
    is_cancelled                  INTEGER,
    profit_margin_pct             NUMERIC(12, 6)
);

